/* Burnley (Belgrave, Lilydale, Alamein and Glen Waverley) lines */

#pragma once

#include "hwconfig/led_matrix.h"

/* Belgrave line */
#define LMAT_BELGRAVE_BEG                               LMAT_BASE(4, 2, 0)
#define LMAT_BELGRAVE_BEG_ALT                           LMAT_BASE(4, 2, 1)
#define LMAT_BELGRAVE_TCM                               LMAT_BASE(4, 2, 2)
#define LMAT_BELGRAVE_TCM_ALT                           LMAT_BASE(4, 2, 3)
#define LMAT_BELGRAVE_UPW                               LMAT_BASE(4, 2, 4)
#define LMAT_BELGRAVE_UPW_ALT                           LMAT_BASE(4, 2, 5)
#define LMAT_BELGRAVE_UFG                               LMAT_BASE(4, 3, 0)
#define LMAT_BELGRAVE_UFG_ALT                           LMAT_BASE(4, 3, 1)
#define LMAT_BELGRAVE_FTG                               LMAT_BASE(4, 3, 2)
#define LMAT_BELGRAVE_FTG_ALT                           LMAT_BASE(4, 3, 3)
#define LMAT_BELGRAVE_BOR                               LMAT_BASE(4, 3, 4)
#define LMAT_BELGRAVE_BOR_ALT                           LMAT_BASE(4, 3, 5)
#define LMAT_BELGRAVE_BAY                               LMAT_BASE(4, 4, 0)
#define LMAT_BELGRAVE_BAY_ALT                           LMAT_BASE(4, 4, 1)
#define LMAT_BELGRAVE_HMT                               LMAT_BASE(4, 4, 2)
#define LMAT_BELGRAVE_HMT_ALT                           LMAT_BASE(4, 4, 3)

/* Lilydale line */
#define LMAT_LILYDALE_LIL                               LMAT_BASE(4, 10, 0)
#define LMAT_LILYDALE_LIL_ALT                           LMAT_BASE(4, 10, 1)
#define LMAT_LILYDALE_MLK                               LMAT_BASE(4, 10, 2)
#define LMAT_LILYDALE_MLK_ALT                           LMAT_BASE(4, 10, 3)
#define LMAT_LILYDALE_CDN                               LMAT_BASE(4, 10, 4)
#define LMAT_LILYDALE_CDN_ALT                           LMAT_BASE(4, 10, 5)
#define LMAT_LILYDALE_RWE                               LMAT_BASE(4, 11, 0)
#define LMAT_LILYDALE_RWE_ALT                           LMAT_BASE(4, 11, 1)

/* Ringwood shared line */
#define LMAT_RINGWOOD_RWD                               LMAT_BASE(4, 4, 4)
#define LMAT_RINGWOOD_RWD_ALT                           LMAT_BASE(4, 4, 5)
#define LMAT_RINGWOOD_HTD                               LMAT_BASE(4, 5, 0)
#define LMAT_RINGWOOD_HTD_ALT                           LMAT_BASE(4, 5, 1)
#define LMAT_RINGWOOD_MCH                               LMAT_BASE(4, 5, 2)
#define LMAT_RINGWOOD_MCH_ALT                           LMAT_BASE(4, 5, 3)
#define LMAT_RINGWOOD_NWG                               LMAT_BASE(4, 5, 4)
#define LMAT_RINGWOOD_NWG_ALT                           LMAT_BASE(4, 5, 5)
#define LMAT_RINGWOOD_BBN                               LMAT_BASE(4, 6, 0)
#define LMAT_RINGWOOD_BBN_ALT                           LMAT_BASE(4, 6, 1)
#define LMAT_RINGWOOD_LAB                               LMAT_BASE(4, 6, 2)
#define LMAT_RINGWOOD_LAB_ALT                           LMAT_BASE(4, 6, 3)
#define LMAT_RINGWOOD_BOX                               LMAT_BASE(4, 6, 4)
#define LMAT_RINGWOOD_BOX_ALT                           LMAT_BASE(4, 6, 5)
#define LMAT_RINGWOOD_UNN                               LMAT_BASE(4, 7, 0)
#define LMAT_RINGWOOD_UNN_ALT                           LMAT_BASE(4, 7, 1)
#define LMAT_RINGWOOD_CHM                               LMAT_BASE(4, 7, 2)
#define LMAT_RINGWOOD_CHM_ALT                           LMAT_BASE(4, 7, 3)
#define LMAT_RINGWOOD_CBY                               LMAT_BASE(4, 7, 4)
#define LMAT_RINGWOOD_CBY_ALT                           LMAT_BASE(4, 7, 5)
#define LMAT_RINGWOOD_ECM                               LMAT_BASE(4, 8, 0)
#define LMAT_RINGWOOD_ECM_ALT                           LMAT_BASE(4, 8, 1)

/* Alamein line */
#define LMAT_ALAMEIN_ALM                                LMAT_BASE(5, 0, 0)
#define LMAT_ALAMEIN_ALM_ALT                            LMAT_BASE(5, 0, 1)
#define LMAT_ALAMEIN_ASH                                LMAT_BASE(5, 0, 2)
#define LMAT_ALAMEIN_ASH_ALT                            LMAT_BASE(5, 0, 3)
#define LMAT_ALAMEIN_BWD                                LMAT_BASE(5, 0, 4)
#define LMAT_ALAMEIN_BWD_ALT                            LMAT_BASE(5, 0, 5)
#define LMAT_ALAMEIN_HWL                                LMAT_BASE(5, 1, 0)
#define LMAT_ALAMEIN_HWL_ALT                            LMAT_BASE(5, 1, 1)
#define LMAT_ALAMEIN_WSN                                LMAT_BASE(5, 1, 2)
#define LMAT_ALAMEIN_WSN_ALT                            LMAT_BASE(5, 1, 3)
#define LMAT_ALAMEIN_RIV                                LMAT_BASE(5, 1, 4)
#define LMAT_ALAMEIN_RIV_ALT                            LMAT_BASE(5, 1, 5)

/* Camberwell shared line */
#define LMAT_CAMBERWELL_CAM                             LMAT_BASE(4, 8, 2)
#define LMAT_CAMBERWELL_CAM_ALT                         LMAT_BASE(4, 8, 3)
#define LMAT_CAMBERWELL_AUB                             LMAT_BASE(4, 8, 4)
#define LMAT_CAMBERWELL_AUB_ALT                         LMAT_BASE(4, 8, 5)
#define LMAT_CAMBERWELL_GFE                             LMAT_BASE(4, 9, 0)
#define LMAT_CAMBERWELL_GFE_ALT                         LMAT_BASE(4, 9, 1)
#define LMAT_CAMBERWELL_HAW                             LMAT_BASE(4, 9, 2)
#define LMAT_CAMBERWELL_HAW_ALT                         LMAT_BASE(4, 9, 3)

/* Glen Waverley line */
#define LMAT_WAVERLEY_GWY                               LMAT_BASE(5, 2, 0)
#define LMAT_WAVERLEY_GWY_ALT                           LMAT_BASE(5, 2, 1)
#define LMAT_WAVERLEY_SYN                               LMAT_BASE(5, 2, 2)
#define LMAT_WAVERLEY_SYN_ALT                           LMAT_BASE(5, 2, 3)
#define LMAT_WAVERLEY_MWY                               LMAT_BASE(5, 2, 4)
#define LMAT_WAVERLEY_MWY_ALT                           LMAT_BASE(5, 2, 5)
#define LMAT_WAVERLEY_JOR                               LMAT_BASE(5, 3, 0)
#define LMAT_WAVERLEY_JOR_ALT                           LMAT_BASE(5, 3, 1)
#define LMAT_WAVERLEY_HOL                               LMAT_BASE(5, 3, 2)
#define LMAT_WAVERLEY_HOL_ALT                           LMAT_BASE(5, 3, 3)
#define LMAT_WAVERLEY_EMV                               LMAT_BASE(5, 3, 4)
#define LMAT_WAVERLEY_EMV_ALT                           LMAT_BASE(5, 3, 5)
#define LMAT_WAVERLEY_DLG                               LMAT_BASE(5, 4, 0)
#define LMAT_WAVERLEY_DLG_ALT                           LMAT_BASE(5, 4, 1)
#define LMAT_WAVERLEY_GIR                               LMAT_BASE(5, 4, 2)
#define LMAT_WAVERLEY_GIR_ALT                           LMAT_BASE(5, 4, 3)
#define LMAT_WAVERLEY_GAR                               LMAT_BASE(5, 4, 4)
#define LMAT_WAVERLEY_GAR_ALT                           LMAT_BASE(5, 4, 5)
#define LMAT_WAVERLEY_TGA                               LMAT_BASE(5, 5, 0)
#define LMAT_WAVERLEY_TGA_ALT                           LMAT_BASE(5, 5, 1)
#define LMAT_WAVERLEY_KYG                               LMAT_BASE(5, 5, 2)
#define LMAT_WAVERLEY_KYG_ALT                           LMAT_BASE(5, 5, 3)
#define LMAT_WAVERLEY_HEY                               LMAT_BASE(5, 5, 4)
#define LMAT_WAVERLEY_HEY_ALT                           LMAT_BASE(5, 5, 5)

/* Burnley group shared line */
#define LMAT_BURNLEY_BLY                                LMAT_BASE(4, 9, 4)
#define LMAT_BURNLEY_BLY_ALT                            LMAT_BASE(4, 9, 5)
#define LMAT_BURNLEY_ERM                                LMAT_BASE(4, 1, 4)
#define LMAT_BURNLEY_ERM_ALT                            LMAT_BASE(4, 1, 5)
#define LMAT_BURNLEY_RMD                                LMAT_BASE(2, 11, 4)
#define LMAT_BURNLEY_RMD_ALT                            LMAT_BASE(2, 11, 5)

/* city stations */
#define LMAT_BURNLEY_SSS                                LMAT_BASE(2, 2, 0)
#define LMAT_BURNLEY_SSS_ALT                            LMAT_BASE(2, 2, 1)
#define LMAT_BURNLEY_FGS                                LMAT_BASE(2, 3, 2)
#define LMAT_BURNLEY_FGS_ALT                            LMAT_BASE(2, 3, 3)
#define LMAT_BURNLEY_MCE                                LMAT_BASE(2, 4, 2)
#define LMAT_BURNLEY_MCE_ALT                            LMAT_BASE(2, 4, 3)
#define LMAT_BURNLEY_PAR                                LMAT_BASE(2, 5, 2)
#define LMAT_BURNLEY_PAR_ALT                            LMAT_BASE(2, 5, 3)
#define LMAT_BURNLEY_FSS                                LMAT_BASE(2, 8, 4)

